// Auto-generated by `supabase gen types typescript --linked`.
// Do not edit by hand. To refresh after a migration, run:
//   pnpm dlx supabase@latest gen types typescript --linked > types/database.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      ai_insights: {
        Row: {
          contact_id: string
          content: string
          expires_at: string
          generated_at: string
          id: string
          insight_type: string
          is_stale: boolean
          model_version: string
          org_id: string
        }
        Insert: {
          contact_id: string
          content: string
          expires_at: string
          generated_at?: string
          id?: string
          insight_type: string
          is_stale?: boolean
          model_version?: string
          org_id: string
        }
        Update: {
          contact_id?: string
          content?: string
          expires_at?: string
          generated_at?: string
          id?: string
          insight_type?: string
          is_stale?: boolean
          model_version?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_insights_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_insights_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          city: string | null
          company: string | null
          country: string | null
          created_at: string
          email: string | null
          embedding: string | null
          first_name: string | null
          hubspot_id: string
          hubspot_updated_at: string | null
          id: string
          is_archived: boolean
          job_title: string | null
          last_name: string | null
          lead_status: string | null
          lifecycle_stage: string | null
          local_updated_at: string
          org_id: string
          phone: string | null
          properties: Json
          sync_hash: string | null
          sync_status: string
          base_state: Json | null
          updated_at: string
          website: string | null
        }
        Insert: {
          city?: string | null
          company?: string | null
          base_state?: Json | null
          country?: string | null
          created_at?: string
          email?: string | null
          embedding?: string | null
          first_name?: string | null
          hubspot_id: string
          hubspot_updated_at?: string | null
          id?: string
          is_archived?: boolean
          job_title?: string | null
          last_name?: string | null
          lead_status?: string | null
          lifecycle_stage?: string | null
          local_updated_at?: string
          org_id: string
          phone?: string | null
          properties?: Json
          sync_hash?: string | null
          sync_status?: string
          updated_at?: string
          website?: string | null
        }
        Update: {
          city?: string | null
          company?: string | null
          country?: string | null
          created_at?: string
          email?: string | null
          embedding?: string | null
          first_name?: string | null
          hubspot_id?: string
          hubspot_updated_at?: string | null
          id?: string
          is_archived?: boolean
          job_title?: string | null
          last_name?: string | null
          lead_status?: string | null
          lifecycle_stage?: string | null
          local_updated_at?: string
          org_id?: string
          phone?: string | null
          properties?: Json
          sync_hash?: string | null
          sync_status?: string
          base_state?: Json | null
          updated_at?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      hubspot_connections: {
        Row: {
          access_token_secret: string | null
          connected_at: string
          connected_by: string | null
          id: string
          last_synced_at: string | null
          needs_reconnect: boolean
          org_id: string
          portal_id: string
          portal_name: string | null
          refresh_token_secret: string | null
          scopes: string[] | null
          token_expires_at: string | null
        }
        Insert: {
          access_token_secret?: string | null
          connected_at?: string
          connected_by?: string | null
          id?: string
          last_synced_at?: string | null
          needs_reconnect?: boolean
          org_id: string
          portal_id: string
          portal_name?: string | null
          refresh_token_secret?: string | null
          scopes?: string[] | null
          token_expires_at?: string | null
        }
        Update: {
          access_token_secret?: string | null
          connected_at?: string
          connected_by?: string | null
          id?: string
          last_synced_at?: string | null
          needs_reconnect?: boolean
          org_id?: string
          portal_id?: string
          portal_name?: string | null
          refresh_token_secret?: string | null
          scopes?: string[] | null
          token_expires_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "hubspot_connections_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          id: string
          org_id: string
          type: "agent_run" | "conflict" | "hubspot_update" | "sync_error"
          title: string
          body: string | null
          link: string | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          type: "agent_run" | "conflict" | "hubspot_update" | "sync_error"
          title: string
          body?: string | null
          link?: string | null
          read?: boolean
          created_at?: string
        }
        Update: { read?: boolean }
        Relationships: []
      }
      contact_notes: {
        Row: {
          id: string
          org_id: string
          contact_id: string
          user_id: string | null
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          contact_id: string
          user_id?: string | null
          content: string
          created_at?: string
        }
        Update: {
          content?: string
        }
        Relationships: []
      }
      agent_actions: {
        Row: {
          id: string
          org_id: string
          contact_id: string | null
          run_id: string
          action_type: "follow_up_email" | "re_engagement" | "risk_alert" | "opportunity"
          title: string
          reasoning: string
          draft_subject: string | null
          draft_body: string | null
          status: "pending" | "approved" | "dismissed" | "acted"
          created_at: string
          acted_at: string | null
        }
        Insert: {
          id?: string
          org_id: string
          contact_id?: string | null
          run_id: string
          action_type: "follow_up_email" | "re_engagement" | "risk_alert" | "opportunity"
          title: string
          reasoning: string
          draft_subject?: string | null
          draft_body?: string | null
          status?: "pending" | "approved" | "dismissed" | "acted"
          created_at?: string
          acted_at?: string | null
        }
        Update: {
          id?: string
          org_id?: string
          contact_id?: string | null
          run_id?: string
          action_type?: "follow_up_email" | "re_engagement" | "risk_alert" | "opportunity"
          title?: string
          reasoning?: string
          draft_subject?: string | null
          draft_body?: string | null
          status?: "pending" | "approved" | "dismissed" | "acted"
          created_at?: string
          acted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_actions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "agent_actions_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
        ]
      }
      org_ai_cache: {
        Row: {
          id: string
          org_id: string
          cache_key: string
          content: Json
          generated_at: string
          expires_at: string
        }
        Insert: {
          id?: string
          org_id: string
          cache_key: string
          content: Json
          generated_at?: string
          expires_at: string
        }
        Update: {
          id?: string
          org_id?: string
          cache_key?: string
          content?: Json
          generated_at?: string
          expires_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "org_ai_cache_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          email_domain: string | null
          id: string
          industry: string | null
          name: string
        }
        Insert: {
          created_at?: string
          email_domain?: string | null
          id?: string
          industry?: string | null
          name: string
        }
        Update: {
          created_at?: string
          email_domain?: string | null
          id?: string
          industry?: string | null
          name?: string
        }
        Relationships: []
      }
      sync_events: {
        Row: {
          after_state: Json | null
          before_state: Json | null
          contact_id: string | null
          created_at: string
          direction: string
          error_message: string | null
          event_type: string
          hubspot_id: string | null
          id: string
          org_id: string
        }
        Insert: {
          after_state?: Json | null
          before_state?: Json | null
          contact_id?: string | null
          created_at?: string
          direction: string
          error_message?: string | null
          event_type: string
          hubspot_id?: string | null
          id?: string
          org_id: string
        }
        Update: {
          after_state?: Json | null
          before_state?: Json | null
          contact_id?: string | null
          created_at?: string
          direction?: string
          error_message?: string | null
          event_type?: string
          hubspot_id?: string | null
          id?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sync_events_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sync_events_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_hubspot_token_secret: {
        Args: { label: string; token: string }
        Returns: string
      }
      get_hubspot_token_secret: { Args: { secret_id: string }; Returns: string }
      match_contacts: {
        Args: {
          match_count?: number
          match_org_id: string
          match_threshold?: number
          query_embedding: string
        }
        Returns: {
          company: string
          country: string
          email: string
          first_name: string
          id: string
          job_title: string
          last_name: string
          lead_status: string
          lifecycle_stage: string
          local_updated_at: string
          similarity: number
          sync_status: string
        }[]
      }
      match_messages: {
        Args: {
          query_embedding: string
          match_user_id: string
          match_org_id: string
          match_threshold?: number
          match_count?: number
        }
        Returns: {
          id: string
          role: string
          content: string
          conversation_id: string
          created_at: string
          similarity: number
        }[]
      }
      update_hubspot_token_secret: {
        Args: { new_token: string; secret_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
